### ISSUE TITLE
No Bitlocker drives found!

### ISSUE THREAD

**Issue by PROBLEMCHYLD** [raryelcostasouza/dislocker-gui-zenity#1]
All I get is an error No Bitlocker drives found!

Possible fix but it doesn't work either.
https://translate.google.com/translate?hl=en&sl=ru&u=https://www.i-holder.net/articles/linux-debian/130-bitlocker-under-linux-user-mounted&prev=search

**Comment by raryelcostasouza** [comment]
Thanks for providing feedback so the software can be improved.

The version available at the link you send has some modifications from my original code  (https://github.com/raryelcostasouza/dislocker-gui-zenity/releases) so I cannot be sure. Did you try to run the version available on my github account?

What filesystem is used on your bitlocker drive? Is it NTFS? 

If it is FAT probably is not going to be detected... I mistakely assumed that Bitlocker could only be used with exFAT and NTFS. I will work on fixing that.

**Comment by PROBLEMCHYLD** [comment]
I used both versions, yours and the modified version neither seem to work with FAT. I use all formats, FAT exFAT, NTFS etc... It would be nice to have your script work with all formats. Thanks for the speedy response, which makes you a true computer GEEK!!!! LOL.....

**Comment by raryelcostasouza** [comment]
I think I might have found a solution... please try the following

on file util-root.sh

on the line:
fdisk -l | grep NTFS | cut -c6-9 > /tmp/fdisk.txt

change to:
fdisk -l | grep 'FAT32\|NTFS' | cut -c6-9 > /tmp/fdisk.txt

Check if the FAT Bitlocker drive get detected...
Thanks

**Comment by raryelcostasouza** [comment]
I think I might have found a solution... please try the following

on file util-root.sh

on the line:
fdisk -l | grep NTFS | cut -c6-9 > /tmp/fdisk.txt

change to:
fdisk -l | grep 'FAT32\|NTFS' | cut -c6-9 > /tmp/fdisk.txt

Check if the FAT Bitlocker drive get detected...
Thanks

**Comment by raryelcostasouza** [comment]
I think I might have found a solution... please try the following

on file util-root.sh

on the line:
fdisk -l | grep NTFS | cut -c6-9 > /tmp/fdisk.txt

change to:
fdisk -l | grep 'FAT32\\|NTFS' | cut -c6-9 > /tmp/fdisk.txt

Check if the FAT Bitlocker drive get detected...
Thanks

**Comment by raryelcostasouza** [comment]
Make sure to include the backslash before the vertical bar before NTFS... the github editor automatically removed the first time I saved the comment...

**Comment by PROBLEMCHYLD** [comment]
I still get the error on USB and internal drives.

**Comment by raryelcostasouza** [comment]
Could you please provide me the output of the following command (with your bitlocker drives connected):

sudo fdisk -l

**Comment by PROBLEMCHYLD** [comment]
Adding this line       lsblk -l -n > /tmp/fdisk.txt works. Thank you

**Comment by PROBLEMCHYLD** [comment]
Seems to be read-only

**Comment by raryelcostasouza** [comment]
The command you suggest may work, but it shows all partitions on system without filtering... for the next version I would like it to still filter out only the FAT and NTFS partitions to test if they are or not Bitlocker encrypted, saving unnecessary tests. In that way, could you please provide me the output of the command on a terminal:
sudo fdisk -l 

Thanks in advance,

**Comment by PROBLEMCHYLD** [comment]
fdisk -l

Disk /dev/ram0: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram1: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram2: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram3: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram4: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram5: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram6: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram7: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram8: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram9: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram10: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram11: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram12: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram13: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram14: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram15: 16 MiB, 16777216 bytes, 32768 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/sda: 465.8 GiB, 500107862016 bytes, 976773168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 30FBB73D-21F3-4F52-8E20-5833C8466C19

Device         Start       End   Sectors   Size Type
/dev/sda1       2048    206847    204800   100M EFI System
/dev/sda2     206848    468991    262144   128M Microsoft reserved
/dev/sda3     468992 104859647 104390656  49.8G Microsoft basic data
/dev/sda4  104859648 897081343 792221696 377.8G Microsoft basic data
/dev/sda5  897081344 959995903  62914560    30G Linux filesystem
/dev/sda6  959995904 976773119  16777216     8G Linux swap


Disk /dev/loop0: 14.6 GiB, 15663611392 bytes, 30592991 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x6f20736b

Device       Boot      Start        End    Sectors   Size Id Type
/dev/loop0p1       778135908 1919645538 1141509631 544.3G 72 unknown
/dev/loop0p2       168689522 2104717761 1936028240 923.2G 65 Novell Netware 386
/dev/loop0p3      1869881465 3805909656 1936028192 923.2G 79 unknown
/dev/loop0p4      2885681152 2885736650      55499  27.1M  d unknown

Partition table entries are not in disk order.


Disk /dev/sdb: 14.6 GiB, 15664676864 bytes, 30595072 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: FE67D15D-6CD7-4C72-BE68-9D548B2438FB

Device     Start      End  Sectors  Size Type
/dev/sdb1   2048 30595038 30592991 14.6G Microsoft basic data

**Comment by PROBLEMCHYLD** [comment]
Adding mount -o loop,rw,uid=1000,gid=1000 $DFILE_LOCATION/dislocker-file $DRIVE_MOUNTPOINT allows me to read and write

**Comment by raryelcostasouza** [comment]
Thanks for the information requested... 
So the proper replacement for the line:

fdisk -l | grep NTFS | cut -c6-9 > /tmp/fdisk.txt
would be
fdisk -l | grep 'FAT32\\|NTFS\\|Microsoft' | cut -c6-9 > /tmp/fdisk.txt

That would only test microsoft partitions for bitlocker drives... the proper way. I will add this change to the next version... coming out soon.

About the read only mount... I will have to investigate further... 
What distro are you using? 
What's the output of 
ls-lhas /media
ls -lhas /media/BitLockerDrive/

**Comment by PROBLEMCHYLD** [comment]
[root@darkstar:~] # ls-lhas /media
-su: ls-lhas: command not found
[root@darkstar:~] # ls -lhas /media/BitLockerDrive/
total 1.2M
8.0K drwxr-xr-x  8 problemchyld 1000 8.0K Dec 31  1969 .
4.0K drwxr-xr-x 17 root         root 4.0K Apr  6 16:37 ..
8.0K -rwxr-xr-x  1 problemchyld 1000  122 Mar  5 11:21 autorun.inf
8.0K drwxr-xr-x  4 problemchyld 1000 8.0K Mar  5 11:21 boot
376K -rwxr-xr-x  1 problemchyld 1000 375K Mar  5 11:21 bootmgr
656K -rwxr-xr-x  1 problemchyld 1000 654K Mar  5 11:21 bootmgr.efi
8.0K drwxr-xr-x  4 problemchyld 1000 8.0K Mar  5 11:21 efi
112K -rwxr-xr-x  1 problemchyld 1000 105K Mar  5 11:21 setup.exe
 16K drwxr-xr-x 10 problemchyld 1000  16K Mar  5 11:21 sources
8.0K drwxr-xr-x  5 problemchyld 1000 8.0K Mar  5 11:36 support
8.0K drwxr-xr-x  2 problemchyld 1000 8.0K Apr  4 10:48 System Volume Information
8.0K drwxr-xr-x  3 problemchyld 1000 8.0K Mar  5 11:36 upgrade

The new command fdisk -l | grep 'FAT32\|NTFS\|Microsoft' | cut -c6-9 > /tmp/fdisk.txt works and faster. Thanks infinity.

**Comment by raryelcostasouza** [comment]
Sorry I mistyped...
ls -lhas /media 

About the permission problem... how are you running the main app?
1) use the icon?
or 
2) use the dislocker-gui.sh as root?
or
3) use the dislocker-gui.sh as normal user?

It should be always executed as normal user... otherwise may cause permission problems like read only...

**Comment by PROBLEMCHYLD** [comment]
dislocker-gui.sh as user problemchyld. I'm using Slackware Linux. When I add uid and gid, I have full read and write access.

**Comment by PROBLEMCHYLD** [comment]
Does the script decrypt multiple drives at once? If not, would be a nice feature.

**Comment by raryelcostasouza** [comment]
In regards to the read only permission that is a bit curious... on Fedora and Gentoo it was never necessary to supply the uid and gid on the mount command.. but both on your Slackware and my Manjaro it is necessary... maybe newer versions changes, etc...

the uid and gid are unique for each user... so the generic solution so it works for any user account... it is better to do:

mount -o loop,rw,uid=$UID,gid=$GROUPS $DFILE_LOCATION/dislocker-file $DRIVE_MOUNTPOINT

A new version is coming soon including these fixes and support for mounting multiple drives simultaneously... 

I just noticed that the latest version of gnome-disks (3.32)  is able to detect the bitlocker partition and even offers a option to unlock it... but as far as I tried it did not work... maybe in future versions.

By the way... if you are the owner of the russian website referred on the first post, please edit the source files to keep at least the copyright header (first line) and the name of the license GPL3 (don't need to put the whole license header).

Thanks for providing the feedback and also the suggestions of solutions. It was very helpful for the improvement of the app.

**Comment by PROBLEMCHYLD** [comment]
Thank you and appreciate your work.  Looking forward to the new release.

**Comment by raryelcostasouza** [comment]
New stable version released at https://github.com/raryelcostasouza/dislocker-gui-zenity/releases/tag/v2.0

**Comment by PROBLEMCHYLD** [comment]
Everything works great!!! I made a couple of personal changes, changed name to BitUnlocker, and the width on boxes. Thanks for the fixes, everything seems to work really great.

![Screenshot_2019-04-09_15-46-46](https://user-images.githubusercontent.com/30463992/55834196-f1f33c00-5ade-11e9-9b68-3d66423b9097.png)
![Screenshot_2019-04-08_09-27-39](https://user-images.githubusercontent.com/30463992/55732349-71024a80-59e1-11e9-88d1-abce9117a54e.png)

**Comment by PROBLEMCHYLD** [comment]
The width of the boxes should expand based on the drives detected. IDK, just a thought. Thanks again...
